[phases.setup]
aptPkgs = [
  "wget",
  "ca-certificates",
  "libgconf-2-4",
  "libnss3",
  "libxss1",
  "libasound2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libglib2.0-0",
  "libgtk-3-0",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libxshmfence1"
]
